<?php

    $list = $this->getListExpertReview();

?>

<h1>Expert Review</h1>

<table class="table table-striped table-bordered table-hover text-center">
    <thead>
    <tr>
        <th>#</th>
        <th>Title</th>
        <th>Expert Name</th>
        <th>Product Name</th>
        <th>Video</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($list as $index => $item){
        echo
        '
            <tr>
                <td>'. $index + 1 .'</td>
                <td>'. $item['review_title'] .'</td>
                <td>'. $item['expert_name'] .'</td>
                <td>'. $item['product_name'] .'</td>
                <td></td>
                <td>
                <a href="http://magento.conf/admin/catalog/product/edit/id/'. $item['product_id'] .'">Detail</a>
</td>
            </tr>
        ';
    }?>


    </tbody>
</table>

