<?php
/**
 * @var $block Dev\Banner\Block\Widget\Slider
 */
$images = $block->getBanners();

?>

<!DOCTYPE html>
<html>
    <body>
    <h3><?= $block->escapeHtml($block->getData('title')) ?></h3>
        <div class="slick-slider">
            <?php
                foreach ($images as $image) {
                    echo
                        '
                            <div>
                                <img class="item" src="'.$image.'"  width="100%"/>
                            </div>
                        ';
                }
                ?>
        </div>
    </body>
</html>
