<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product view template
 *
 * @var $block Description
 */
/**
 * @var $viewModel ProductContent
 */
$viewModel = $block->getViewModel();

use Magento\Catalog\Block\Product\View\Description;
use Product\Content\ViewModel\ProductContent;
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
    <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
        <?php if ($renderLabel) :?>
            <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
        <?php endif; ?>
<!--        Add content top-->
        <?php foreach ($viewModel->getDisplayArea() as $index => $item): ?>
            <?php if($item == 0) : ?>
                <div><?= $viewModel->filterOutputHtml($viewModel->getContent()[$index]) ?></div>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue  ?></div>
<!--        add content bottom-->
        <?php foreach ($viewModel->getDisplayArea() as $index => $item): ?>
            <?php if($item == 1) : ?>
                <div><?= $viewModel->filterOutputHtml($viewModel->getContent()[$index]) ?></div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>


