<?php

    $banner = $this->getImageChangeBanner();

//    css ẩn banner gốc nếu tồn tại $banner

    if(!empty($banner)) {
        echo
        '
        <style>
            .block-promo{
                display: none;
            }
        </style>
        ';
    }

?>

<!DOCTYPE html>
<html>
<body>
    <section class="regular slider">
        <?php
            foreach ($banner as $value) {
                echo
                '
                <div>
                    <img src="'.$value['image'].'" style="width: 100%; " />
                </div>
                ';
            }
        ?>
    </section>
</body>
</html>





