
<!--// Get order by function getOrder in Block/Adminhtml/CustomDonate.php-->
<?php $order = $this->getOrder(); ?>
<?php if ($order) : ?>
    <!--    Show option Donate Checkout trong in order admin  -->
    <section class="admin__page-section order-additional-information">
        <div class="admin__page-section-title">
            <strong class="title"><?php echo /* @escapeNotVerified */ __('Donate Checkout'); ?></strong>
        </div>
        <div id="<?php echo $this->getHtmlId() ?>"
             class="admin__page-section-content order-additional-information-container">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th>Amount Donate</th>
                            <td><?php echo '$ '. number_format($order['custom_donate'], 2, ',', '.'); ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
